myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('post_create', views.PostCreate.as_view(), name='post_create'),
    path('post_detail/<int:pk>', views.PostDetail.as_view(), name='post_detail'),
    path('post_update/<int:pk>', views.PostUpdate.as_view(), name='post_update'),
    path('post_delete/<int:pk>', views.PostDelete.as_view(), name='post_delete'),
    path('post_list', views.PostList.as_view(), name='post_list')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # 追加
    state = models.IntegerField(default=1)

    def __str__(self):
        return self.title

myapp/forms.py
from django import forms
from . models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'state')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            print('############')
            print(field.widget)

myapp/views.py
from django.shortcuts import render, resolve_url
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView
from . models import Post
from django.urls import reverse_lazy
from . forms import PostForm
from django.contrib import messages


# Create your views here.
class Index(TemplateView):
    template_name = 'myapp/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = Post.objects.all()
        context = {
            'post_list': post_list,
        }
        return context

class PostCreate(CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('myapp:index')

class PostDetail(DetailView):
    model = Post

class PostUpdate(UpdateView):
    model = Post
    form_class = PostForm

    def get_success_url(self):
        messages.success(self.request, 'Postを更新しました。')
        return resolve_url('myapp:post_detail', pk=self.kwargs['pk'])

class PostDelete(DeleteView):
    model = Post

    def get_success_url(self):
        messages.success(self.request, 'Postを削除しました。')
        return resolve_url('myapp:index')

class PostList(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(state=1).order_by('-created_at')

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Mp</title>
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.2.0/mdb.min.css" rel="stylesheet" />
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Navbar brand -->
            <a class="navbar-brand" href="/">My Blog</a>

            <!-- Toggle button -->
            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left links -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'myapp:post_create' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">管理画面</a>
                    </li>
                    <!-- Navbar dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-mdb-toggle="dropdown" aria-expanded="false">
                            Post
                        </a>
                        <!-- Dropdown menu -->
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'myapp:post_create' %}">新規投稿</a></li>
                            <li><a class="dropdown-item" href="{% url 'myapp:post_list' %}">投稿一覧</a></li>
                            <li>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
                <!-- Left links -->

                <!-- Search form -->
                <form class="d-flex input-group w-auto">
                    <input type="search" class="form-control" placeholder="Type query" aria-label="Search" />
                    <button class="btn btn-outline-primary" type="button" data-mdb-ripple-color="dark">
                        Search
                    </button>
                </form>
            </div>
            <!-- Collapsible wrapper -->
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->

    <main class="container">
        {% if messages %}
        <ul class="messages mt-2">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{message}}
            </div>
            {% endfor %}
        </ul>
        {% endif %}

        {% block content %}
        {% endblock %}
    </main>


    <footer class="bg-primary text-white text-center text-lg-start">
        <!-- Grid container -->
        <div class="container p-4">
            <!--Grid row-->
            <div class="row">
                <!--Grid column-->
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Footer Content</h5>

                    <p>
                        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
                        molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
                        voluptatem veniam, est atque cumque eum delectus sint!
                    </p>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Links</h5>

                    <ul class="list-unstyled mb-0">
                        <li>
                            <a href="#!" class="text-white">Link 1</a>
                        </li>
                        <li>
                            <a href="#!" class="text-white">Link 2</a>
                        </li>
                        <li>
                            <a href="#!" class="text-white">Link 3</a>
                        </li>
                        <li>
                            <a href="#!" class="text-white">Link 4</a>
                        </li>
                    </ul>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase mb-0">Links</h5>

                    <ul class="list-unstyled">
                        <li>
                            <a href="#!" class="text-white">Link 1</a>
                        </li>
                        <li>
                            <a href="#!" class="text-white">Link 2</a>
                        </li>
                        <li>
                            <a href="#!" class="text-white">Link 3</a>
                        </li>
                        <li>
                            <a href="#!" class="text-white">Link 4</a>
                        </li>
                    </ul>
                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->
        </div>
        <!-- Grid container -->

        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
            © 2020 Copyright:
            <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.2.0/mdb.min.js"></script>
</body>

</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 g-4 mt-2 mb-4">
    {% for item in post_list %}
    <div class="col">
        <div class="card">
            <img src="https://mdbootstrap.com/img/new/standard/city/041.jpg" class="card-img-top" alt="..." />
            <div class="card-body">
                <h5 class="card-title">{{item.title}}</h5>
                <p class="card-text">{{item.content}}</p>
                <a href="{% url 'myapp:post_detail' item.id %}" type="submit" class="btn btn-primary">もっと読む</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

myapp/templates/myapp/post_confirm_delete.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-9">
        <br>
        <h2>Post削除</h2>
        <br>

        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p>以下の内容を削除しますか？</p>
                <input type="submit" class="btn btn-danger" value="削除する">
            </form>
        </div>

        <p>　タイトル</p>
        {{object.title}}
        <hr>
        <p>内容</p>
        {{object.content}}
        <hr>
    </div>

</div>


{% endblock %}

myapp/templates/myapp/post_detail.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-9 mt-2 mb-2">
        <div class="card">
            <img src="https://mdbootstrap.com/img/new/standard/nature/184.jpg" class="card-img-top" alt="..." />
            <div class="card-body">
                <h5 class="card-title">{{object.title}}</h5>
                <p class="card-text">{{object.content}}</p>
                {% if object.state == 1 %}
                <p>公開済み</p>
                {% endif %}
                <a href="{% url 'myapp:post_update' object.pk %}" class="btn btn-primary">更新</a>
                <a href="{% url 'myapp:post_delete' object.pk %}" class="btn btn-danger">削除</a>

            </div>
        </div>
    </div>
</div>

{% endblock %}

myapp/templates/myapp/post_form.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-9">
        <br>
        <h2>登録・更新ページ</h2>
        <br>

        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>タイトル</label>
                {{form.title}}
            </div>
            <br>
            <div class="form-group">
                <label>内容</label>
                {{form.content}}
            </div>
            <br>
            <div class="form-group">
                <label>公開</label>
                {{form.state}}
            </div>
            <button type="submit" class="btn btn-primary mb-2">保存</button>
            <br>
        </form>
    </div>
</div>


{% endblock %}

myapp/templates/myapp/post_list.html
{% extends 'myapp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-9">
        <br>
        <h2>Post一覧</h2>
        <br>
        <table class="table">
            <thead>
                <tr>
                    <th>タイトル</th>
                    <th>内容</th>
                    <th>作成日</th>
                    <th>更新日</th>
                </tr>
            </thead>
            <tbody>
                {% for item in post_list %}
                <tr>
                    <td><a href="{% url 'myapp:post_detail' item.pk %}">{{item.title}}</a></td>
                    <td>{{item.content}}</td>
                    <td>{{item.created_at}}</td>
                    <td>{{item.updated_at}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>


    </div>
</div>


{% endblock %}